

server:
  port: 4000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Employee_management?useSSL=false&serverTimezone=UTC
    username: root
    password: mysql@123A
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
